source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'JSONJoy-Swift', '~> 1.0.0'
pod 'SwiftHTTP', '~>1.0.0'
pod 'OAuthSwift', '~> 0.5.0'
